name: file_state_manager
description: "This package allows you to easily undo and redo saved data in your applications."
version: 1.1.2
repository: https://github.com/MasahideMori-SimpleAppli/file_state_manager

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
